blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ GitHub Discussions
    url: https://github.com/WeenSpace/weenspace/discussions
    about: If you have a support question or need help getting WeenSpace to work, please use GitHub Discussions.
